# Generated by Django 5.2.17 on 2026-09-09 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="The page this keyword targets."
                    ),
                ),
                ("current_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("target_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("search_volume", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0-100, e.g. an SEO tool's keyword difficulty score.",
                        null=True,
                    ),
                ),
                ("last_checked", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["current_rank", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="KeywordRankHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "checked_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="keywords.keyword",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "keyword rank history",
                "ordering": ["-checked_on"],
            },
        ),
    ]
