# Generated by Django 5.2.17 on 2026-09-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_keyword", models.CharField(max_length=255)),
                (
                    "competitor_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional: competitor URLs/titles or notes to consider.",
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=255)),
                ("h1", models.CharField(blank=True, max_length=255)),
                (
                    "headings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered [{level, text}] outline.",
                    ),
                ),
                ("faq", models.JSONField(blank=True, default=list)),
                ("related_keywords", models.JSONField(blank=True, default=list)),
                (
                    "internal_link_suggestions",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "target_word_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cta_suggestion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_briefs",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_briefs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
