# Generated by Django 5.2.17 on 2026-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="search_console_site_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
