# Generated by Django 5.2.17 on 2026-09-11 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_search_console_site_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "received_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «قسط اول»، «تسویه نهایی»، شماره فاکتور و...",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-created_at"],
            },
        ),
    ]
