# Generated by Django 5.2.17 on 2026-09-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="For staff accounts: the Owner account whose business they work on.",
                limit_choices_to={"role": "owner"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
