# Generated by Django 5.2.17 on 2026-09-22 09:19

from django.db import migrations, models


def backfill_order(apps, schema_editor):
    """Give every existing task an order matching its current
    (deadline, -priority) position, per project — so upgrading doesn't
    visually scramble task lists that used to rely on that ordering."""
    Task = apps.get_model("tasks", "Task")
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        tasks = Task.objects.filter(project=project).order_by("deadline", "-priority")
        for index, task in enumerate(tasks):
            task.order = index
        Task.objects.bulk_update(tasks, ["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_persian_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order", "deadline", "-priority"]},
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_order, migrations.RunPython.noop),
    ]
